from typing import Any
from pydantic import BaseModel, Field


class CreateMessageRequest(BaseModel):
    """Create message request validation
    Users can only send 'text' or 'path' type messages.
    System types ('code', 'file_request') are generated by AI.
    """
    type: str = Field(pattern=r'^(text|path)$')
    content: str = Field(min_length=1)
    data: str = ''


class FileMappingItem(BaseModel):
    slot_label: str
    file_id: int
    original_name: str
    stored_name: str = ""


class ConfirmUploadRequest(BaseModel):
    task_uuid: str
    project_id: int
    file_mappings: list[FileMappingItem]
    primer_f: str = ""
    primer_r: str = ""
