from pydantic import BaseModel, Field


class CreateMessageRequest(BaseModel):
    """Create message request validation
    Users can only send 'text' or 'path' type messages.
    System types ('code', 'file_request') are generated by AI.
    """
    type: str = Field(pattern=r'^(text|path)$')
    content: str = Field(min_length=1)
    data: str = ''
